apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xnew2w684-java-springboot
  janus-idp.io/tekton: xnew2w684-java-springboot
  backstage.io/kubernetes-id: xnew2w684-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xnew2w684-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
